Reworked admin pages for 2.1 compliance and general look and layout improvement
Tinyportal/TinyPortal pull request #80
Opened 2018-09-07 19:36 UTC by ArjenWelling

This is ready as far as I am concerned: many edits and all tested locally against 2.0 and 2.1.

- Removed news section in admin (following earlier changes illori)
- All TP admin pages updated in line with 2.1 responsive styling
- Shoutbox admin pages updated in line with 2.1 responsive styling
- Responsive theme selection now shows .png files in 2.1
- Fixed overflow issue with links in menu item overviews
- Added toggle all options in block admin page for showing blocks in articles / categories

2018-09-07 20:19 UTC, tinoest requested changes

2018-09-07 20:19 UTC, tinoest commented on Themes/default/TPortalAdmin.template.php
> +					<br  /><input type="checkbox" onclick="invertAll(this, this.form, \'tpb'.$block['id'].'\');" />'.$txt['tp-checkall'],'<br><br>
You missed this br  /

2018-09-08 08:14 UTC, ArjenWelling commented on Themes/default/TPortalAdmin.template.php
> +					<br  /><input type="checkbox" onclick="invertAll(this, this.form, \'tpb'.$block['id'].'\');" />'.$txt['tp-checkall'],'<br><br>
Yep, but to be fair I only did the template file. We should really do all files at some point...

2018-09-08 08:25 UTC, Bopske commented on Themes/default/TPortalAdmin.template.php
> +					<br  /><input type="checkbox" onclick="invertAll(this, this.form, \'tpb'.$block['id'].'\');" />'.$txt['tp-checkall'],'<br><br>
Updated this one and also update the other template files in the PR

2018-09-08 15:37 UTC, merged